/**
 * TEMPORARY stand-in for `packages/stdb-bindings` (generated by Backend at CP0).
 * The real module exports a generated `DbConnection` class. Until it exists,
 * live mode reports "bindings not generated" instead of connecting.
 */
export const DbConnection: unknown = null;
